services:
  #Materiais
  myst:
    image: darlon/myst:0.2
    container_name: myst
    user: 1000:1000
    ports:
      - 3000:3000
      - 3100:3100
    volumes:
      - ./:/data
    working_dir: /data
    command: ./myst_start.sh
    restart: always

  jlab:
    image: darlon/myst:0.2-jlab
    container_name: myst-jlab
    profiles: [ 'full', 'jlab' ]
    user: 1000:1000
    volumes:
      - ./:/data
    ports:
      - "8890:8888"
    working_dir: /data
    restart: always

  full:
    image: darlon/myst:0.2-full
    container_name: myst-full
    profiles: [ 'full' ]
    volumes:
      - ./:/data
    working_dir: /data
    # command: npx docusaurus build


  bash:
    image: darlon/myst:0.2
    container_name: myst_bash
    profiles: [ 'bash' ]
    stdin_open: true #docker run -i
    tty: true #docker run -t
    volumes:
      - ./:/data
    working_dir: /data
    command: /bin/bash

  version:
    image: darlon/myst:0.2
    profiles: [ 'version' ]
    command: myst --version
