FROM node:20 AS myst_server

RUN apt update
RUN apt -y install python3-pip python3-virtualenv webp
RUN mkdir /data
WORKDIR /data

RUN virtualenv /env
ENV PATH="/env/bin:$PATH"
RUN pip3 install -U mystmd

FROM myst_server AS myst_latex
#Latex
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt -y install latexmk tzdata texlive-xetex texlive-fonts-extra texlive-fonts-recommended lmodern

WORKDIR /data




